package kw.learn.meiju;

public enum ItemType {
    HIGHTSHADOW, SATURATION,LUMIN,EDG,EXPOSURE,
    DISSOLVE,NOISEONE,SOLARIZE,EDG2,GRAY,GRAY2,
    CONTRAST,GAMMA,COLORINERT,PIX,HUE,BRIGHT,SEPIA,
    SHARPEN,HREOHOLD,POSTER
}
